language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t costalago/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true costalago/udemy-docker-react npm run test -- --coverage